import type { Metadata } from "next";
import { Roboto_Mono as RobotoMono } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";

const robotoMono = RobotoMono({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  children: ReactNode;
}

export default function (props: Props) {
  return (
    <html lang="en">
      <body className={robotoMono.className}>{props.children}</body>
    </html>
  );
}
